<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookMyMark.AppService\BookMyMark.AppService.csproj" />
    <ProjectReference Include="..\BookMyMark.Command\BookMyMark.Command.csproj" />
    <ProjectReference Include="..\BookMyMark.DTO\BookMyMark.DTO.csproj" />
    <ProjectReference Include="..\BookMyMark.Infrastructure\BookMyMark.Infrastructure.csproj" />
    <ProjectReference Include="..\BookMyMark.Query\BookMyMark.Query.csproj" />
    <ProjectReference Include="..\BookMyMark.Shared\BookMyMark.Shared.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Data\books.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
