<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookMyMark.Shared\BookMyMark.Shared.csproj" />
    <ProjectReference Include="..\BookMyMark.DTO\BookMyMark.DTO.csproj" />
    <ProjectReference Include="..\BookMyMark.Infrastructure\BookMyMark.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
